/**
 * ZENITH NORTH — Native Compliant Messaging
 *
 * Built to satisfy SEC Rule 17a-4 audit-trail alternative
 * and Investment Advisers Act Rule 204-2.
 *
 * REGULATORY BASIS:
 *
 * The 2022 SEC amendments to Rule 17a-4 allow firms to use
 * an "audit-trail alternative" instead of WORM storage. This
 * requires a system that:
 *
 *   (1) Maintains records in a manner that permits recreation
 *       of the original if modified or deleted
 *   (2) Has an audit trail of every access and change
 *   (3) Makes records immediately accessible to regulators
 *   (4) Stores records for the required retention period
 *   (5) Maintains duplicate copies at separate locations
 *
 * HOW ZENITH NORTH SATISFIES EACH REQUIREMENT:
 *
 *   (1) Communications are INSERT-only. The RLS policy blocks
 *       DELETE and UPDATE at the database level. The original
 *       is always the only version. Recreation is trivial.
 *
 *   (2) Every send, read, review, and export is written to
 *       the audit_log table. That table also blocks DELETE
 *       and UPDATE via RLS. The trail is complete and immutable.
 *
 *   (3) The exam package generator produces all records for
 *       any client, advisor, or date range in seconds. The
 *       CCO (Designated Executive Officer) has direct DB access
 *       credentials as required by the amended rule.
 *
 *   (4) Retention policies are stored per-record-type in the
 *       retention_policies table. Communications are retained
 *       for 3 years minimum (5 years for Zenith North default),
 *       with the first 2 years immediately accessible.
 *
 *   (5) Neon PostgreSQL replicates data across multiple
 *       availability zones automatically. The primary and
 *       replica are in separate geographic locations.
 *       Firms on Professional plan get cross-region replication.
 *
 * DESIGNATED EXECUTIVE OFFICER (DEO):
 *   Under the amended rule, the firm's CCO signs a written
 *   undertaking (generated by Zenith North) agreeing to provide
 *   records to the SEC upon request. This is included in the
 *   firm's Master Service Agreement and generated automatically
 *   during firm onboarding.
 *
 * SMS DELIVERY:
 *   Uses Twilio — the same carrier infrastructure that MyRepChat
 *   is built on. We pay wholesale instead of retail. Twilio
 *   handles 10DLC registration, carrier compliance, and TCPA
 *   opt-out management.
 *
 * WHAT THIS MEANS FOR SALES:
 *   "Your communications are stored in an immutable, encrypted
 *   database that satisfies SEC Rule 17a-4's audit-trail
 *   alternative. Every message is logged, searchable, and
 *   producible in seconds. Your CCO signs a one-page undertaking
 *   and you're covered. No third-party archiving subscription
 *   required."
 */

// This file documents the architecture.
// Implementation is split across:
//   - src/server/routers/messages.ts (send/receive/review)
//   - src/app/api/sms/route.ts (Twilio webhook)
//   - src/lib/messaging/twilio.ts (SMS delivery)
//   - src/lib/messaging/retention.ts (retention enforcement)
//   - src/lib/messaging/deo.ts (DEO undertaking generation)

export const COMPLIANCE_FRAMEWORK = {
  primaryRule:      'SEC Investment Advisers Act Rule 204-2',
  alternativeRoute: 'SEC Rule 17a-4(f) audit-trail alternative (2022 amendments)',
  retentionYears:   5,    // SEC minimum is 3; we default to 5
  accessibleYears:  2,    // First 2 years immediately accessible
  storageMethod:    'audit-trail',
  storageProvider:  'Neon PostgreSQL — multi-AZ replication',
  encryption:       'AES-256 at rest, TLS 1.3 in transit',
  immutability:     'PostgreSQL RLS policy — DELETE and UPDATE blocked at DB level',
  deoRequired:      true, // Designated Executive Officer undertaking
  channels:         ['platform', 'sms', 'email_log', 'phone_log'],
} as const
